name: ML CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Train model
      run: python train.py

    - name: Test model
      run: python model.py
